### PR TITLE
Added angular package

### PR DESCRIPTION
**Pull request by Pranshu321**

### CODE REVIEW

**Review by sanjeev-scm — COMMENTED** [review]
01. The name of the components for FilterComponentComponent and CardsComponentComponent needs to be changed to  FilterComponent, CardsComponent
02. Make all the property names as camelCase for consistency.
03. Make all the method names camelCase
04. The service file is empty. Can refactor api.ts code in FilteringService

**Review by sanjeev-scm — COMMENTED** [review]
01. The name of the components for FilterComponentComponent and CardsComponentComponent needs to be changed to  FilterComponent, CardsComponent
02. Make all the property names as camelCase for consistency.
03. Make all the method names camelCase
04. The service file is empty. Can refactor api.ts code in FilteringService

**Review by sanjeev-scm — COMMENTED** [review]
01. The name of the components for FilterComponentComponent and CardsComponentComponent needs to be changed to  FilterComponent, CardsComponent
02. Make all the property names as camelCase for consistency.
03. Make all the method names camelCase
04. The service file is empty. Can refactor api.ts code in FilteringService 
05. Rename Interfaces directory as models
06. The input object structures can also be defined as models.
07. Please clarify what is the purpose of the package-test

Please do the above changes

**Comment by Pranshu321** [comment]
> 1. The name of the components for FilterComponentComponent and CardsComponentComponent needs to be changed to  FilterComponent, CardsComponent
> 2. Make all the property names as camelCase for consistency.
> 3. Make all the method names camelCase
> 4. The service file is empty. Can refactor api.ts code in FilteringService
> 5. Rename Interfaces directory as models
> 6. The input object structures can also be defined as models.
> 7. Please clarify what is the purpose of the package-test
> 
> Please do the above changes

Sir I implemented all the changes that you proposed and the answer of question that you asked is that **package-test** is for testing of the package **filtering** how it will behave in real life applications.

**Review by sanjeev-scm — CHANGES_REQUESTED** [review]
01. Change the FilterComponent and CardsComponent spec files too.

02. interfaces.ts file, make all property names as lowerCamelCase
This applies to all properties and function / method names and style sheet selectors

lowerCamelCase :
lowerCamelCase is a naming convention in which a name contains multiple words that are joined together as a single word. In terms of capitalization, the first word is always all lowercase letters, including the first letter.

03. Rename Service_Function_Interfaces.ts to serviceFunctionInterfaces.ts / serviceInterface.ts 
as it is looking odd.

04. Correct the Readme document.
Change react to Angular library
Modify the document as per the new directory structure

**Review by sanjeev-scm — APPROVED** [review]
Change apiService as ApiService

And then you can ask Komal to Merge.

**Pull request merged**
